name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Generate docs
      run: |
        git fetch --prune --unshallow --tags
        sudo gem install jazzy
        jazzy --module-version "$(git describe --tags --abbrev=0)" --github-file-prefix "https://github.com/theos/orion/tree/${GITHUB_SHA}" -o ../docs
    - uses: actions/checkout@v2
      with:
        ref: docs
    - name: Commit docs
      run: |
        cp -a .git ../docs
        cd ../docs
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git commit -am "Update docs: ${GITHUB_SHA}"
        git push
