name: Update Docs

on:
  push:
    tags:
    - '*'

jobs:
  docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        path: master-branch
    - uses: actions/checkout@v2
      with:
        ref: docs
        path: docs-branch
    - name: Update docs
      run: |
        cd master-branch
        version="${GITHUB_REF#refs/tags/}"

        for v in `sort -rV <(printf '%s\n%s' "${version}" "$(ls ../docs-branch/versions)")`; do
          base="$(basename "${v}")"
          echo "- [${base}](/versions/${base})" >> "Guides/Versions.md"
        done

        sudo gem install jazzy
        ./generate-docs.sh "${GITHUB_SHA}" "${version}"

        cd ../docs-branch
        mkdir -p versions
        mv ../docs-perm "versions/${version}"
        mv versions .git ../docs
        cd ../docs

        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add -A
        git commit -m "[docs] Update to ${version}"
        git push
